### ISSUE TITLE
how load it inside express html page?

### ISSUE THREAD

**Issue by bymaximus** [RobertMenke/rm-emoji-picker#37] opened 2017-09-09 06:57 UTC
can you explain me how I can use this from inside express html page? Import statment doesnt work(due chorme version)

**Comment by RobertMenke** [comment] 2017-09-20 21:20
Hey @bymaximus you're correct that the import statement only works in Chrome 61 and beyond. Originally, this tool was intended for people using a bundling tool like webpack, browserify, requireJS, etc. In a future update I will be adding a standalone file intended for use in script tags as a global variable.

If you really need this right now, you can pull down the code from this repo and edit webpack.config.js line 25 so that the `libraryTarget` is `var` instead of `umd`. Once you've done this, cd into the directory for this project and run `npm start` from your terminal. That command will build you a file in `dist/emojipicker.js` that can be loaded from a script tag as a global variable.

I'm going to close this for now, but feel free to re-open this issue if you have trouble.

**Closed by RobertMenke** 2017-09-20 21:20 UTC
